### ISSUE TITLE
有关util.py代码

### ISSUE THREAD

**Issue by a726** [fjchange/pytorch_ano_pre#1]
您好！想请教您一下，这个代码是pytorch环境下运行，在util.py中又加载了tensorflow这个要怎么运行？  期待您的回复!

**Comment by fjchange** [comment]
注释掉就好

**Comment by a726** [comment]
谢谢啊 &nbsp;我注释掉了 &nbsp;但是还有错误 &nbsp;我就先放着了 &nbsp;您运行出来了没？



---原始邮件---
发件人: "kiwi_fung"<notifications@github.com&gt;
发送时间: 2019年10月9日(星期三) 晚上6:26
收件人: "fjchange/pytorch_ano_pre"<pytorch_ano_pre@noreply.github.com&gt;;
抄送: "Xiaoyuan Zhang"<306835421@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [fjchange/pytorch_ano_pre] 有关util.py代码 (#1)



Closed #1.
