### ISSUE TITLE
运行错误TypeError: zip argument #1 must support iteration

### ISSUE THREAD

**Issue by a726** [fjchange/pytorch_ano_pre#2]
您好，运行train.py出现了下面的错误，这个是怎么回事？在网上没有查到解决方案。
(pytorch) E:\pytorch_ano_pre-master\ano_pre>python train.py
initializing the model with Generator-Unet 4 layers,PixelDiscriminator with filters [128, 256, 512, 512]
Traceback (most recent call last):
  File "train.py", line 217, in <module>
    train(num_clips,num_unet_layers,num_channels*(num_clips-num_his),num_channels,discriminator_channels)
  File "train.py", line 126, in train
    for (input,_),(test_input,_) in zip(dataset_loader,test_dataloader):
TypeError: zip argument #1 must support iteration

(pytorch) E:\pytorch_ano_pre-master\ano_pre>Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\admin\Anaconda3\envs\pytorch\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\admin\Anaconda3\envs\pytorch\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input
期待您的回复

**Comment by fjchange** [comment]
请检查路径是否正确，查看下zip()里内容是否为空，代码应该是没错的

**Comment by a726** [comment]
好 &nbsp;那我再研究研究 &nbsp; 谢谢你！
有问题再请教你！非常感谢你回复我！



---原始邮件---
发件人: "kiwi_fung"<notifications@github.com&gt;
发送时间: 2019年10月9日(星期三) 晚上6:31
收件人: "fjchange/pytorch_ano_pre"<pytorch_ano_pre@noreply.github.com&gt;;
抄送: "Xiaoyuan Zhang"<306835421@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [fjchange/pytorch_ano_pre] 运行错误TypeError: zip argument #1 must support iteration (#2)



你检查路径是否正确，查看下zip()里内容是否为空，代码应该是没错的
