### ISSUE TITLE
运行train.py 

### ISSUE THREAD

**Issue by a726** [fjchange/pytorch_ano_pre#3]
你好 运行train.py时出现以下问题：
C:\Users\admin\Anaconda3\envs\pytorch\python.exe E:/pytorch_ano_pre-master/train.py
initializing the model with Generator-Unet 4 layers,PixelDiscriminator with filters [128, 256, 512, 512] 
Traceback (most recent call last):
  File "E:/pytorch_ano_pre-master/train.py", line 217, in <module>
    train(num_clips,num_unet_layers,num_channels*(num_clips-num_his),num_channels,discriminator_channels)
  File "E:/pytorch_ano_pre-master/train.py", line 126, in train
    for (input,_),(test_input,_) in zip(dataset_loader,test_dataloader):
TypeError: zip argument #1 must support iteration
请问这个错误要怎么改？期待您的回复!

**Comment by fjchange** [comment]
1. 代码update到最新
2. 关于pytorch的dataloader和zip的问题 建议google或者baidu

**Comment by a726** [comment]
> 代码update到最新
> 关于pytorch的dataloader和zip的问题 建议google或者baidu

谢谢您的回复!这个问题已经解决了，但是在训练的时候又出现了下面的问题：
##### optimal result and model = dataset = ped2, loss file = ../psnr/ano_pred_ped2_generator_2.pth-2000, auc = 0.8501552234495705
dataset = ped2, loss file = ../psnr/ano_pred_ped2_generator_2.pth-2000, auc = 0.8501552234495705
Traceback (most recent call last):
  File "E:/pytorch_ano_pre-master/ano_pre/train.py", line 219, in <module>
    train(num_clips,num_unet_layers,num_channels*(num_clips-num_his),num_channels,discriminator_channels)
  File "E:/pytorch_ano_pre-master/ano_pre/train.py", line 215, in train
    writer.add_scalar('results/auc', auc, global_step=step)
  File "C:\Users\admin\Anaconda3\envs\pytorch\lib\site-packages\tensorboardX\writer.py", line 342, in add_scalar
    scalar(tag, scalar_value), global_step, walltime)
  File "C:\Users\admin\Anaconda3\envs\pytorch\lib\site-packages\tensorboardX\summary.py", line 120, in scalar
    scalar = make_np(scalar)
  File "C:\Users\admin\Anaconda3\envs\pytorch\lib\site-packages\tensorboardX\x2num.py", line 24, in make_np
    'Got {}, but expected numpy array or torch tensor.'.format(type(x)))
NotImplementedError: Got <class 'NoneType'>, but expected numpy array or torch tensor.
这个应该从哪里看如何修改？
还有一个问题是在train.py中直接运行就不仅训练了，在2000次的倍数的时候还会直接测试出来AUC，不用进行python evaluate.py就可以了？在train.py有注释掉的test这个需要注意吗？最近在看这个方向的，不太懂，期待您的解答！非常感谢您！

**Comment by fjchange** [comment]
事实上，一边运行一边测试时不合理，不过我这里只是为了显示出随着训练过程的增多的结果不断优化，并不是为了调参，你可以就注释掉train.py中的evaluate部分
这里是返回的不是numpy array，可以np.array([auc])代替auc。
另外，很多基础细节，请尽量百度、谷歌，我并不能一一详答复。
感谢你对我工作的关注。

**Comment by a726** [comment]
> 事实上，一边运行一边测试时不合理，不过我这里只是为了显示出随着训练过程的增多的结果不断优化，并不是为了调参，你可以就注释掉train.py中的evaluate部分
> 这里是返回的不是numpy array，可以np.array([auc])代替auc。
> 另外，很多基础细节，请尽量百度、谷歌，我并不能一一详答复。
> 感谢你对我工作的关注。

收到，谢谢您百忙之中回复我，因为编程底子太差，所以可能百度也不能解决问题，但是还是很感谢您！
